### ISSUE TITLE
Ssh-keygen not presented

### ISSUE THREAD

**Issue by sspakush** [actions/actions-runner-controller#2152] opened 2023-01-13 09:01 UTC
### Checks

- [X] I've already read https://github.com/actions/actions-runner-controller/blob/master/TROUBLESHOOTING.md and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I'm not using a custom entrypoint in my runner image

### Controller Version

2.300.2

### Helm Chart Version

v0.21.0

### CertManager Version

1.9.1

### Deployment Method

Helm

### cert-manager installation

yes

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions). It might also be a good idea to contract with any of contributors and maintainers if your business is so critical and therefore you need priority support
- [X] I've read [releasenotes](https://github.com/actions/actions-runner-controller/tree/master/docs/releasenotes) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes
- [X] My actions-runner-controller version (v0.x.y) does support the feature
- [X] I've already upgraded ARC (including the CRDs, see charts/actions-runner-controller/docs/UPGRADING.md for details) to the latest and it didn't fix the issue
- [X] I've migrated to the workflow job webhook event (if you using webhook driven scaling)

### Resource Definitions

```yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
spec:
  organization: org
  dockerEnabled: true
  dockerMTU: 1300
#  dockerdWithinRunnerContainer: true
  labels:
    - docker-runner
  # Other mandatory fields from StatefulSet
  selector:
    matchLabels:
      app: runners
  serviceName: runners
  template:
    metadata:
      labels:
        app: runners
```

### To Reproduce

```markdown
add action with ssh keys
```

### Describe the bug

We use an actions with ssh-keygen.
After migration to runners v2.300.2  we face a problem: "Error: Unable to locate executable file: ssh-keygen. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable."

### Describe the expected behavior

I believe that need to add ssh-keygen package

### Whole Controller Logs

```shell
Logs in controller are of no interest
```

### Whole Runner Pod Logs

```shell
Logs in controller are of no interest
```

### Additional Context

Github action log:
Error: Error: Unable to locate executable file: ssh-keygen. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by sspakush** [comment] 2023-01-13 10:00
UPD. ssh package is not presented too. Could you add it to images?

**Comment by yoshz** [comment] 2023-01-13 11:19
Same here with ssh-agent. All our pipelines are broken now.

**Comment by raffis** [comment] 2023-01-13 11:23
What actually happened is that :latest points now to the ubuntu 22.04 image and not 20.04. That image does not contain ssh packages, also some other things are different like the $PATH var and likely many other things.
Also broke many of our actions.

A quick workaround is to pin the runners to the v20.04 version.

See #2056

**Comment by sspakush** [comment] 2023-01-13 11:23
@yoshz we performed rollback to image: summerwind/actions-runner:v2.299.1-ubuntu-20.04 and pipelines works well but it's a temporary fix...

**Comment by yoshz** [comment] 2023-01-13 11:33
@sspakush That indeed works. But based on @raffis comment I switched to `summerwind/actions-runner:ubuntu-20.04` as the problem is indeed that `latest` is pointing to `summerwind/actions-runner:ubuntu-22.04`.

**Comment by raffis** [comment] 2023-01-13 11:41
> @sspakush That indeed works. But based on @raffis comment I switched to `summerwind/actions-runner:ubuntu-20.04` as the problem is indeed that `latest` is pointing to `summerwind/actions-runner:ubuntu-22.04`.

That works, just adding here that it seems that `summerwind/actions-runner:ubuntu-20.04` does not point to the latest version, 
`summerwind/actions-runner:v2.300.2-ubuntu-20.04` would be the latest working 20.04 version. Seems there is no moving tag anymore for 20.04 (neither for 22.04).

**Comment by sspakush** [comment] 2023-01-13 11:43
@yoshz @raffis you are right, but I preferred to fix also the version. Just in case =)

**Comment by Link-** [comment] 2023-01-18 11:45
For everyone in this thread, `latest` tag is deprecated and will be removed.

https://github.com/actions/actions-runner-controller/issues/2056

Even though the tag was applied by mistake as we migrated the workflows, please use a more specific version of the runner tag in your setups.

I'm closing this issue now as the conversation for what to include in the ubuntu-22.04 image is still open: https://github.com/actions/actions-runner-controller/pull/2098#issuecomment-1357895373

**Closed as completed by Link-** 2023-01-18 11:45 UTC
Labels: bug, needs triage
