### ISSUE TITLE
Multiple label support for gha-runner-scale-set

### ISSUE THREAD

**Issue by tiithansen** [actions/actions-runner-controller#2445] opened 2023-03-25 14:45 UTC
### What would you like added?

Currently it is possible to set only one label gha-runner-scale-set through `runnerScaleSetName`. It would be nice it there would be `runnerSetLabels` which would take in array of labels.

Example:
```yaml
runnerSetName: 'generic'
runnerSetLabels:
- self-hosted
- arm64
```

### Why is this needed?

In previous versions of ARC it was possible to set multiple labels and self-hosted was sort of default label. Having this feature would enable easier switch from ARC to gha-runner-scale-set because it wouldn't be necessary to modify `runs-on: [...]` in workflows which already have these labels in place.

### Additional context

It seems to possible to pass in multiple labels for the runnerScaleSet [code](https://github.com/actions/actions-runner-controller/blob/64cedff2b42790afc00f7ede5a9df897a1afb1ac/controllers/actions.github.com/autoscalingrunnerset_controller.go#L347-L352).

**Comment by jrhemstad** [comment] 2023-06-27 15:41
Agreed, this is important for our use case.

For example, I only have enough Windows test machines to do nightly windows testing. However, during the day, those machines may sit idle and could be repurposed as build machines to improve build job throughput.

Ideally, I could label both my windows build runners with both "windows" and "windows-build" labels, and my test runners as "windows" and "windows-test".

Then I could just specify `runs-on: windows` for my build jobs.

**Comment by dm3ch** [comment] 2023-08-24 14:20
@Link- Could you please point me where I can find information on why it has been decided not to allow support of labels for runnersets?

And is there any chance that it will be added in the future?

```
Labels are not supported and will not be supported for runner scale sets. Please read the docs:

https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/about-actions-runner-controller#using-arc-runners-in-a-workflow
```

**Comment by shakefu** [comment] 2023-08-24 23:53
We also have this use case where we have existing runners labeled `[self-hosted, general-ubuntu]` and we want the scale sets to be able to pick up load from our EC2-based runners using those labels. But since the scale sets are restricted to the single (unique) name as their label, it seems they cannot share load.

From my limited understanding of the code, this seems to be due to the design choice to use k8s labels/annotations on the CRDs as a way to pass the name (label) information to the controller. 

It seems like it would be possible to extend the `AutoscalingListenerSpec` to include a `runnerLabels []string` field which could then be added into the controller reconciliation?

**Comment by nethershaw** [comment] 2023-10-12 22:44
This is absolutely a regression, not an enhancement request. I last deployed ARC for my entire organization at legacy chart version 0.22.0. My entire organization has been using runner labels in a way that absolutely demands multiple labels. I _will not_ force every developer in my organization to rewrite every workflow in my organization to accommodate this artificial limitation.

It's almost as though you don't _want_ me to upgrade from the legacy charts.

**Comment by Link-** [comment] 2023-10-18 08:08
I'm closing this issue as it's a duplicate of this discussion: https://github.com/actions/actions-runner-controller/discussions/2921#discussioncomment-7080396

**Closed as completed by Link-** 2023-10-18 08:08 UTC
Labels: enhancement, needs triage

**Comment by emmahsax** [comment] 2024-02-13 18:53
I just want to add my opinion that this is a huge 👎🏼. It makes it super painful to switch to the new version of runners.
