### ISSUE TITLE
Error: could not download chart: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io: 403 Forbidden<Please write what didn't work for you here>

### ISSUE THREAD

**Issue by bhat39a** [actions/actions-runner-controller#3381] opened 2024-03-25 15:52 UTC
### Checks

- [X] I've already read https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners-with-actions-runner-controller/troubleshooting-actions-runner-controller-errors and I'm sure my issue is not covered in the troubleshooting guide.
- [X] I am using charts that are officially provided

### Controller Version

0.8.3

### Deployment Method

Helm

### Checks

- [X] This isn't a question or user support case (For Q&A and community support, go to [Discussions](https://github.com/actions/actions-runner-controller/discussions)).
- [X] I've read the [Changelog](https://github.com/actions/actions-runner-controller/blob/master/docs/gha-runner-scale-set-controller/README.md#changelog) before submitting this issue and I'm sure it's not due to any recently-introduced backward-incompatible changes

### To Reproduce

```markdown
1. Terraform helm_release not able to download the charts.
2. Bash command is working fine.
```

### Describe the bug

Bash Command Working fine -

NAMESPACE="arc-systems"
helm install arc \
    --namespace "${NAMESPACE}" \
    --create-namespace \
    oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller

But same thing using terraform is throwing error

resource "helm_release" "arc" {
  repository = "oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller"
  chart = "gha-runner-scale-set-controller"
  version = "0.8.3"
  name = "arc"
  namespace = "arc-systems"
  create_namespace = false
}

**Error Message - │ Error: could not download chart: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aactions%2Factions-runner-controller-charts%2Fgha-runner-scale-set-controller%2Fgha-runner-scale-set-controller%3Apull&service=ghcr.io: 403 Forbidden**
│ 

### Describe the expected behavior

Installed the relevant helm charts

### Additional Context

```yaml
NA
```

### Controller Logs

```shell
NA
```

### Runner Pod Logs

```shell
NA
```

**Comment by nikola-jokic** [comment] 2024-03-26 09:24
Hey @bhat39a,

When you do helm pull, it correctly pulls the chart, so it must not be an issue with the chart. I will close this issue since it is not related to ARC. Please redirect the issue to either Terraform or [packages](https://github.com/orgs/community/discussions/categories/packages), wherever you feel is appropriate.

**Closed as completed by nikola-jokic** 2024-03-26 09:24 UTC
Labels: bug, needs triage, gha-runner-scale-set

**Comment by alexkuretz** [comment] 2024-04-02 19:27
The problem is with the formation of the repository URL, this works for me:
```
resource "helm_release" "arc_system" {
  name       = "gha-runner-scale-set-controller"
  repository = "oci://ghcr.io/actions/actions-runner-controller-charts"
  chart      = "gha-runner-scale-set-controller"
  version    = "0.9.0"

  namespace        = local.system_namespace
  create_namespace = true
}
```

**Comment by DavraYoung** [comment] 2025-01-28 18:54
```helm registry logout ghcr.io``` solved the problem

**Comment by andrey-petrenko-develeap** [comment] 2025-05-15 10:42
> `helm registry logout ghcr.io` solved the problem

thank you, that helped!

**Comment by dean-mcb** [comment] 2025-05-16 14:15
Thanks! This worked for me too. (I was running Multi-juicer)
